"""Add consultant onboarding table

Revision ID: 3c4c5bf856a7
Revises: ecd9523ef185
Create Date: 2025-08-04 12:52:22.988552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c4c5bf856a7'
down_revision = 'ecd9523ef185'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
