"""Add consultant_applications table

Revision ID: 708bd9365233
Revises: dfe583ad2b2b
Create Date: 2025-07-30 17:46:03.383598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '708bd9365233'
down_revision = 'dfe583ad2b2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultant_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_legal_name', sa.String(), nullable=False),
    sa.Column('preferred_display_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('mobile_phone', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('city_province', sa.String(), nullable=True),
    sa.Column('time_zone', sa.String(), nullable=True),
    sa.Column('rcic_license_number', sa.String(), nullable=False),
    sa.Column('year_of_initial_licensing', sa.Integer(), nullable=True),
    sa.Column('cicc_membership_status', sa.String(), nullable=True),
    sa.Column('cicc_register_screenshot_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rcic_license_number')
    )
    op.create_index(op.f('ix_consultant_applications_email'), 'consultant_applications', ['email'], unique=True)
    op.create_index(op.f('ix_consultant_applications_id'), 'consultant_applications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consultant_applications_id'), table_name='consultant_applications')
    op.drop_index(op.f('ix_consultant_applications_email'), table_name='consultant_applications')
    op.drop_table('consultant_applications')
    # ### end Alembic commands ###
